Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2021-06, with the labels that each got.

#156 Disable Delete Button if User is not the Author
  src/app/_models/question.ts
  src/app/components/problems/problem-set/problem-set.component.html
  src/test/mock.ts
Labels: bug, enhancement

#159 Order Submissions by Most Recent
  src/app/_services/api/problem/submission.service.ts
  src/app/components/problems/problem-view/problem-view.component.ts
Labels: bug

#162 Use DomSanitizer to Allow for InnerHTML
  src/app/_models/action.ts
  src/app/_models/faq.ts
  src/app/_models/question_submission.ts
  src/app/_services/api/faq.service.ts
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.ts
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.ts
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.html
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/components/problems/problem-view/problem-view.component.html
  src/app/components/problems/problem-view/problem-view.component.ts
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.ts
  src/test/mock.ts
Labels: bug

#164 Refactor services
  .eslintrc.json
  src/app/_services/api.service.ts
  src/app/_services/api/accounts/consent.service.ts
  src/app/_services/api/accounts/profile-details.service.ts
  src/app/_services/api/accounts/register.service.ts
  src/app/_services/api/accounts/reset-password.service.ts
  src/app/_services/api/authentication/authentication.service.ts
  src/app/_services/api/category.service.ts
  src/app/_services/api/contact.service.ts
  src/app/_services/api/course/course-event.service.ts
  src/app/_services/api/faq.service.ts
  src/app/_services/api/problem/difficulty.service.ts
  src/app/_services/api/problem/submission.service.ts
  src/app/_services/api/question.service.ts
  src/app/_services/api/sample-question.service.ts
  src/app/_services/api/schema.service.ts
  src/app/_services/api/token-use.service.ts
  src/app/_services/api/token-values.service.ts
  src/app/_services/api/uqj.service.ts
  src/app/_services/api/user-actions.service.ts
  src/app/_services/api/user-stats.service.ts
  src/app/components/accounts/activation-email/activation-email.component.ts
  src/app/components/accounts/consent-form/consent-form.component.ts
  src/app/components/accounts/profile-details/profile-details.component.ts
  src/app/components/accounts/register/register.component.ts
  src/app/components/accounts/reset-password/reset-password.component.ts
  src/app/components/course/course-registration/course-register.component.ts
  src/app/components/course/token-use-snippet/token-use-snippet.component.spec.ts
  src/app/components/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/components/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/components/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/components/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/components/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
  src/app/components/problems/problem-set/problem-set.component.ts
  src/app/components/problems/problem-view/ace/ace.component.ts
  src/app/components/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/components/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.spec.ts
Labels: enhancement

#174 Fix Parsons Line Indentation Error
  src/app/components/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
Labels: bug

#165 Add Checkbox Support
  src/app/_models/question.ts
  src/app/_models/question_submission.ts
  src/app/_models/uqj.ts
  src/app/_services/problem-helpers.service.ts
  src/app/components/header/header.component.html
  src/app/components/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/components/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/components/problems/problem-create/problem-create.component.html
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.html
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.ts
  src/test/mock.ts
Labels: enhancement

#175 Update CKEditor Version
  angular.json
  package-lock.json
  package.json
Labels: bug

#181 Problem Forms
  src/app/_services/api/question.service.ts
  src/app/_services/problem-helpers.service.spec.ts
  src/app/_services/problem-helpers.service.ts
  src/app/problems/_forms/java.form.ts
  src/app/problems/_forms/mcq.form.ts
  src/app/problems/_forms/parsons.form.ts
  src/app/problems/_forms/problem-set.form.ts
  src/app/problems/ace/ace.component.ts
  src/app/problems/ck-editor/ck-editor.component.ts
  src/app/problems/json-editor/json-editor.component.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
  src/app/problems/problem-set/problem-set.component.html
  src/app/problems/problem-set/problem-set.component.ts
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
Labels: refactor

#187 Changed the filter in the UQJ file and removed the suppress
  src/app/components/course/course-question-snippet/course-question-snippet.component.ts
Labels: bug, refactor

#185 Problem Services
  src/app/_services/api/sample-question.service.spec.ts
  src/app/components/course/course-question-snippet/course-question-snippet.component.ts
  src/app/components/homepage/recent-viewed-questions/recent-viewed-questions.component.ts
  src/app/components/token-values/token-values.component.ts
  src/app/problems/_services/difficulty.service.spec.ts
  src/app/problems/_services/difficulty.service.ts
  src/app/problems/_services/question.service.spec.ts
  src/app/problems/_services/question.service.ts
  src/app/problems/_services/schema.service.spec.ts
  src/app/problems/_services/schema.service.ts
  src/app/problems/_services/submission.service.spec.ts
  src/app/problems/_services/submission.service.ts
  src/app/problems/_services/uqj.service.spec.ts
  src/app/problems/_services/uqj.service.ts
  src/app/problems/json-editor/json-editor.component.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-create/problem-create.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
  src/app/problems/problem-edit/problem-edit.component.ts
  src/app/problems/problem-set/problem-set.component.ts
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
  src/app/problems/problem-view/problem-view.component.ts
  src/app/problems/problems.module.ts
  src/app/problems/submission-view/submission-view.component.ts
Labels: refactor

#183 Refactor course
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/course/course-event-create/course-event-create-edit.component.html
  src/app/course/course-event-create/course-event-create-edit.component.scss
  src/app/course/course-event-create/course-event-create-edit.component.spec.ts
  src/app/course/course-event-create/course-event-create-edit.component.ts
  src/app/course/course-events-snippet/course-events-snippet.component.html
  src/app/course/course-events-snippet/course-events-snippet.component.scss
  src/app/course/course-events-snippet/course-events-snippet.component.spec.ts
  src/app/course/course-events-snippet/course-events-snippet.component.ts
  src/app/course/course-list/course-list.component.html
  src/app/course/course-list/course-list.component.scss
  src/app/course/course-list/course-list.component.spec.ts
  src/app/course/course-list/course-list.component.ts
  src/app/course/course-question-snippet/course-question-snippet.component.html
  src/app/course/course-question-snippet/course-question-snippet.component.scss
  src/app/course/course-question-snippet/course-question-snippet.component.spec.ts
  src/app/course/course-question-snippet/course-question-snippet.component.ts
  src/app/course/course-registration/course-register.component.html
  src/app/course/course-registration/course-register.component.scss
  src/app/course/course-registration/course-register.component.spec.ts
  src/app/course/course-registration/course-register.component.ts
  src/app/course/course-routing.module.ts
  src/app/course/course.component.html
  src/app/course/course.component.scss
  src/app/course/course.component.spec.ts
  src/app/course/course.component.ts
  src/app/course/course.module.ts
  src/app/course/leader-board/leader-board.component.html
  src/app/course/leader-board/leader-board.component.scss
  src/app/course/leader-board/leader-board.component.spec.ts
  src/app/course/leader-board/leader-board.component.ts
  src/app/course/token-use-snippet/token-use-snippet.component.html
  src/app/course/token-use-snippet/token-use-snippet.component.scss
  src/app/course/token-use-snippet/token-use-snippet.component.spec.ts
  src/app/course/token-use-snippet/token-use-snippet.component.ts
Labels: refactor
