Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2021-09, with the labels that each got.

#247 Add `is_verified` to the UI
  src/app/problems/_forms/java.form.ts
  src/app/problems/_forms/mcq.form.ts
  src/app/problems/_forms/parsons.form.ts
  src/app/problems/_test/mock.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
Labels: enhancement

#249 User Actions UI
  src/app/_models/action.ts
  src/app/_services/api/user-actions.service.spec.ts
  src/app/_services/api/user-actions.service.ts
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.ts
  src/app/components/homepage/user-actions/user-actions.component.html
  src/app/components/homepage/user-actions/user-actions.component.spec.ts
  src/app/components/homepage/user-actions/user-actions.component.ts
  src/app/problems/problem-set/problem-set.component.ts
  src/test/mock.ts
  src/test/user-actions.service.mock.ts
Labels: bug, enhancement

#251 Make unused imports errors
  .eslintrc.json
  src/app/course/_test/course-events-snippet/course-events-snippet.component.spec.ts
  src/app/course/_test/course/course.component.spec.ts
  src/app/course/_test/token-use-snippet/token-use-snippet.component.spec.ts
  src/app/problems/_services/submission.service.spec.ts
  src/app/problems/problem-edit/problem-edit.component.ts
Labels: refactor

#253 Contributing guidelines
  .github/CONTRIBUTING.md
Labels: enhancement

#255 Issue template
  .github/issue_template_bug.md
  .github/issue_template_feature.md
Labels: enhancement

#260 Fix Course not Opening Bug
  src/app/components/homepage/course-dashboard/course-dashboard.component.html
Labels: bug

#258 Fix e2e Failure
  .github/workflows/build.yml
  e2e/protractor.conf.js
Labels: bug

#263 Install taiga-ui framework
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
Labels: enhancement

#267 Change Chrome Version
  .github/workflows/build.yml
  package.json
Labels: bug
