Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2021-07, with the labels that each got.

#197 Clear Inputs
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
Labels: bug

#194 Moved services into course module and added providers in the module
  src/app/components/homepage/course-dashboard/course-dashboard.component.ts
  src/app/components/homepage/inactive-courses/inactive-courses.component.ts
  src/app/components/user-stats/user-stats.component.ts
  src/app/course/_services/course-event.service.spec.ts
  src/app/course/_services/course-event.service.ts
  src/app/course/_services/course.service.spec.ts
  src/app/course/_services/course.service.ts
  src/app/course/_services/token-use.service.spec.ts
  src/app/course/_services/token-use.service.ts
  src/app/course/course-event-create/course-event-create-edit.component.ts
  src/app/course/course-events-snippet/course-events-snippet.component.ts
  src/app/course/course-list/course-list.component.ts
  src/app/course/course-question-snippet/course-question-snippet.component.ts
  src/app/course/course-registration/course-register.component.ts
  src/app/course/course.component.ts
  src/app/course/course.module.ts
  src/app/course/token-use-snippet/token-use-snippet.component.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
Labels: refactor

#196 Course forms
  src/app/course/_forms/course-event.form.ts
  src/app/course/_forms/register.form.ts
  src/app/course/course-event-create/course-event-create-edit.component.html
  src/app/course/course-event-create/course-event-create-edit.component.ts
  src/app/course/course-registration/course-register.component.ts
Labels: refactor

#202 Fix the Broken Tests
  src/app/app.module.ts
  src/app/problems/_test/problem-create/java-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/mcq-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/parsons-create-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/java-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/mcq-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/parsons-edit-snippet.component.spec.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.ts
  src/app/problems/problems.module.ts
  src/app/problems/submission-view/submission-view.component.html
Labels: bug

#204 Practice Questions
  src/app/problems/_forms/java.form.ts
  src/app/problems/_forms/mcq.form.ts
  src/app/problems/_forms/parsons.form.ts
  src/app/problems/_test/mock.ts
  src/app/problems/_test/problem-create/java-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/mcq-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/parsons-create-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/java-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/mcq-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/parsons-edit-snippet.component.spec.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
Labels: enhancement

#200 Concept map fix
  src/app/app.module.ts
  src/app/course/concept-map/concept-map-graph.ts
  src/app/course/concept-map/concept-map.component.html
  src/app/course/concept-map/concept-map.component.scss
  src/app/course/concept-map/concept-map.component.spec.ts
  src/app/course/concept-map/concept-map.component.ts
  src/app/course/course.component.html
  src/app/course/course.module.ts
Labels: bug

#207 Display Medium Instead of Normal
  src/app/problems/_test/problem-set/problem-set.component.spec.ts
  src/app/problems/problem-set/problem-set.component.html
  src/app/problems/problem-set/problem-set.component.ts
Labels: bug

#209 Course services testing
  src/app/_models/course-registration/course_registration_response.ts
  src/app/course/_services/course-event.service.spec.ts
  src/app/course/_services/course.service.spec.ts
  src/app/course/_services/token-use.service.spec.ts
  src/app/course/_test/mock.ts
  src/app/course/course-registration/course-register.component.html
  src/app/course/course-registration/course-register.component.ts
  src/app/course/token-use-snippet/token-use-snippet.component.ts
Labels: refactor

#215 Fix Edit Bug
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
Labels: bug

#217 Fix CommonJS Warnings
  angular.json
Labels: bug

#224 Course Edit Bug Fix
  src/app/problems/_test/mock.ts
  src/app/problems/_test/problem-create/java-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/mcq-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/parsons-create-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/java-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/mcq-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/parsons-edit-snippet.component.spec.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
Labels: bug

#226 Fix Java Submission Bug
  src/app/problems/ace/ace.component.html
Labels: bug

#219 Problem create edit form fixes
  src/app/problems/json-editor/json-editor.component.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
Labels: enhancement
