Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2021-08, with the labels that each got.

#229 Ignore Unused Variables in Mock Services
  .eslintrc.json
Labels: bug, enhancement

#239 Consent form
  src/app/_models/user_consent.ts
  src/app/accounts/_forms/consent.form.ts
  src/app/accounts/_services/consent.service.spec.ts
  src/app/accounts/_services/consent.service.ts
  src/app/accounts/_test/consent.service.mock.ts
  src/app/accounts/_test/mock.ts
  src/app/accounts/accounts.module.ts
  src/app/accounts/admin-terms-and-conditions-snippet/admin-terms-and-conditions-snippet.component.html
  src/app/accounts/admin-terms-and-conditions-snippet/admin-terms-and-conditions-snippet.component.scss
  src/app/accounts/admin-terms-and-conditions-snippet/admin-terms-and-conditions-snippet.component.spec.ts
  src/app/accounts/admin-terms-and-conditions-snippet/admin-terms-and-conditions-snippet.component.ts
  src/app/accounts/consent-form/consent-form.component.html
  src/app/accounts/consent-form/consent-form.component.spec.ts
  src/app/accounts/consent-form/consent-form.component.ts
  src/app/accounts/student-terms-and-conditions-snippet/student-terms-and-conditions-snippet.component.html
  src/app/accounts/student-terms-and-conditions-snippet/student-terms-and-conditions-snippet.component.scss
  src/app/accounts/student-terms-and-conditions-snippet/student-terms-and-conditions-snippet.component.spec.ts
  src/app/accounts/student-terms-and-conditions-snippet/student-terms-and-conditions-snippet.component.ts
  src/app/accounts/terms-and-conditions-snippet/terms-and-conditions-snippet.component.html
  src/app/accounts/terms-and-conditions-snippet/terms-and-conditions-snippet.component.ts
Labels: refactor

#238 Concept map fix
  src/app/course/concept-map/concept-map-graph.ts
  src/app/course/concept-map/concept-map.component.html
  src/app/course/concept-map/concept-map.component.scss
Labels: bug

#232 Course components testing and documentation
  src/app/course/_test/concept-map/concept-map.component.spec.ts
  src/app/course/_test/course-event-create-edit/course-event-create-edit.component.spec.ts
  src/app/course/_test/course-events-snippet/course-events-snippet.component.spec.ts
  src/app/course/_test/course-list/course-list.component.spec.ts
  src/app/course/_test/course-question-snippet/course-question-snippet.component.spec.ts
  src/app/course/_test/course-registration/course-register.component.spec.ts
  src/app/course/_test/course/course.component.spec.ts
  src/app/course/_test/leader-board/leader-board.component.spec.ts
  src/app/course/_test/mock.ts
  src/app/course/_test/token-use-snippet/token-use-snippet.component.spec.ts
  src/app/course/_test/token-use.service.mock.ts
  src/app/course/concept-map/concept-map.component.spec.ts
  src/app/course/concept-map/concept-map.component.ts
  src/app/course/course-event-create/course-event-create-edit.component.spec.ts
  src/app/course/course-event-create/course-event-create-edit.component.ts
  src/app/course/course-events-snippet/course-events-snippet.component.spec.ts
  src/app/course/course-events-snippet/course-events-snippet.component.ts
  src/app/course/course-list/course-list.component.spec.ts
  src/app/course/course-list/course-list.component.ts
  src/app/course/course-question-snippet/course-question-snippet.component.spec.ts
  src/app/course/course-question-snippet/course-question-snippet.component.ts
  src/app/course/course-registration/course-register.component.spec.ts
  src/app/course/course-registration/course-register.component.ts
  src/app/course/course.component.spec.ts
  src/app/course/token-use-snippet/token-use-snippet.component.spec.ts
  src/app/course/token-use-snippet/token-use-snippet.component.ts
  src/app/problems/_test/course-event.service.mock.ts
  src/app/problems/_test/uqj.service.mock.ts
  src/test/course.service.mock.ts
Labels: enhancement

#220 Import Events
  src/app/course/_services/course-event.service.spec.ts
  src/app/course/_services/course-event.service.ts
  src/app/course/_test/course-events-snippet/course-events-snippet.component.spec.ts
  src/app/course/course-events-snippet/course-events-snippet.component.html
  src/app/course/course-events-snippet/course-events-snippet.component.ts
  src/app/problems/_test/course-event.service.mock.ts
Labels: enhancement

#240 Add Toastr Testing
  src/app/problems/_test/problem-create/java-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/mcq-create-snippet.component.spec.ts
  src/app/problems/_test/problem-create/parsons-create-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/java-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/mcq-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/parsons-edit-snippet.component.spec.ts
  src/app/problems/_test/problem-edit/problem-edit.component.spec.ts
  src/app/problems/_test/problem-set/problem-set.component.spec.ts
  src/app/problems/_test/problem-view/java-view-snippet.component.spec.ts
  src/app/problems/_test/problem-view/mcq-view-snippet.component.spec.ts
  src/app/problems/_test/problem-view/variable-view.component.spec.ts
  src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
Labels: refactor

#234 Initial API Changes
  src/app/_services/api.service.ts
  src/app/accounts/_services/change-password.service.ts
  src/app/accounts/_services/register.service.ts
  src/app/accounts/_services/reset-password.service.ts
  src/app/accounts/activation-email/activation-email.component.ts
  src/app/accounts/change-password/change-password.component.ts
  src/app/accounts/reset-password/reset-password.component.ts
  src/app/course/_services/token-use.service.ts
  src/app/course/token-use-snippet/token-use-snippet.component.ts
  src/app/problems/_services/question.service.spec.ts
  src/app/problems/_services/question.service.ts
  src/app/problems/_services/submission.service.spec.ts
  src/app/problems/_services/submission.service.ts
  src/app/problems/_test/question.service.mock.ts
  src/app/problems/_test/submission.service.mock.ts
  src/app/problems/problem-set/problem-set.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
Labels: bug
