Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2021-05, with the labels that each got.

#126 Fixes ESLint issues for course
  src/app/_services/api/course/course-event.service.ts
  src/app/components/course/course-event-create/course-event-create-edit.component.html
  src/app/components/course/course-event-create/course-event-create-edit.component.ts
  src/app/components/course/course-events-snippet/course-events-snippet.component.ts
  src/app/components/course/course-list/course-list.component.ts
  src/app/components/course/course-question-snippet/course-question-snippet.component.ts
  src/app/components/course/course-registration/course-register.component.ts
  src/app/components/course/course.component.ts
  src/app/components/course/leader-board/leader-board.component.ts
  src/app/components/course/token-use-snippet/token-use-snippet.component.ts
Labels: bug

#131 Remove New Problem from Admin Dropdown
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: bug

#133 Fix Logo in Accounts
  src/app/components/accounts/consent-form/consent-form.component.html
  src/app/components/accounts/consent-form/consent-form.component.ts
  src/app/components/accounts/login/login.component.html
  src/app/components/accounts/login/login.component.ts
  src/app/components/accounts/profile-details/profile-details.component.html
  src/app/components/accounts/profile-details/profile-details.component.ts
  src/app/components/accounts/register/register.component.html
  src/app/components/accounts/register/register.component.ts
  src/app/components/accounts/reset-password/reset-password.component.html
  src/app/components/accounts/reset-password/reset-password.component.ts
Labels: bug

#136 Lint all services
  src/app/_services/api/accounts/consent.service.ts
  src/app/_services/api/accounts/profile-details.service.ts
  src/app/_services/api/accounts/register.service.ts
  src/app/_services/api/accounts/reset-password.service.ts
  src/app/_services/api/authentication/authentication.service.ts
  src/app/_services/api/category.service.ts
  src/app/_services/api/contact.service.ts
  src/app/_services/api/course/course-event.service.ts
  src/app/_services/api/course/course-registration.service.spec.ts
  src/app/_services/api/course/course-registration.service.ts
  src/app/_services/api/course/course.service.ts
  src/app/_services/api/faq.service.ts
  src/app/_services/api/problem/submission.service.ts
  src/app/_services/api/question.service.ts
  src/app/_services/api/sample-question.service.ts
  src/app/_services/api/schema.service.ts
  src/app/_services/api/token-use.service.ts
  src/app/_services/api/token-values.service.ts
  src/app/_services/api/uqj.service.ts
  src/app/_services/api/user-actions.service.ts
  src/app/_services/api/user-stats.service.ts
  src/app/_services/message.service.ts
  src/app/_services/problem-helpers.service.ts
  src/app/components/accounts/activation-email/activation-email.component.ts
  src/app/components/accounts/profile-details/profile-details.component.ts
  src/app/components/accounts/register/register.component.ts
  src/app/components/accounts/reset-password/reset-password.component.ts
  src/app/components/contact/contact.component.html
  src/app/components/contact/contact.component.ts
  src/app/components/course/course-question-snippet/course-question-snippet.component.ts
  src/app/components/course/course.component.ts
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.ts
  src/app/components/homepage/recent-viewed-questions/recent-viewed-questions.component.ts
  src/app/components/homepage/user-actions/user-actions.component.ts
  src/app/components/problems/problem-set/problem-set.component.html
  src/app/components/problems/problem-set/problem-set.component.ts
Labels: bug

#138 Lint components
  .eslintrc.json
  .github/workflows/build.yml
  src/app/_helpers/auth.guard.ts
  src/app/_helpers/error.interceptor.ts
  src/app/_helpers/jwt.interceptor.ts
  src/app/_models/multiple_choice_question.ts
  src/app/_models/question.ts
  src/app/_models/uqj.ts
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/concept-map/concept-map-graph.ts
  src/app/components/concept-map/concept-map.component.ts
  src/app/components/header/header.component.ts
  src/app/components/homepage/course-dashboard/course-dashboard.component.ts
  src/app/components/homepage/homepage.component.ts
  src/app/components/homepage/inactive-courses/inactive-courses.component.ts
  src/app/components/homepage/recent-viewed-questions/recent-viewed-questions.component.ts
  src/app/components/landing-page/landing-page.component.ts
  src/app/components/messages/messages.component.ts
  src/app/components/problems/json-editor/json-editor.component.ts
  src/app/components/problems/problem-create/java-create-snippet/java-create-snippet.component.html
  src/app/components/problems/problem-create/java-create-snippet/java-create-snippet.component.ts
  src/app/components/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.html
  src/app/components/problems/problem-create/mcq-create-snippet/mcq-create-snippet.component.ts
  src/app/components/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.html
  src/app/components/problems/problem-create/parsons-create-snippet/parsons-create-snippet.component.ts
  src/app/components/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.html
  src/app/components/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.spec.ts
  src/app/components/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.html
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.spec.ts
  src/app/components/problems/problem-edit/mcq-edit-snippet/mcq-edit-snippet.component.ts
  src/app/components/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.html
  src/app/components/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.spec.ts
  src/app/components/problems/problem-edit/parsons-edit-snippet/parsons-edit-snippet.component.ts
  src/app/components/problems/problem-edit/problem-edit.component.html
  src/app/components/problems/problem-edit/problem-edit.component.ts
  src/app/components/problems/problem-set/problem-set.component.ts
  src/app/components/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.html
  src/app/components/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/components/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
  src/app/components/problems/problem-view/submission-snippet/submission-snippet.component.ts
  src/app/components/problems/problem-view/variable-view/variable-view.component.ts
  src/app/components/sample-questions/sample-questions.component.ts
  src/app/components/token-values/token-values.component.ts
  src/app/components/topics/topics.component.ts
  src/environments/environment.ts
  src/main.ts
  src/test.ts
  src/test/mock.ts
  tsconfig.json
Labels: bug

#145 Subcategory filter and problem set filters refactoring
  src/app/_services/api/question.service.ts
  src/app/components/problems/problem-set/problem-set.component.html
  src/app/components/problems/problem-set/problem-set.component.ts
Labels: enhancement

#147 index.html to 404.html
  .github/workflows/build.yml
  package.json
Labels: bug

#149 Update README.md
  README.md
Labels: documentation

#142 Removing "registered"
  src/app/_models/course.ts
  src/app/_services/api/course/course.service.ts
  src/app/_services/api/token-use.service.ts
  src/app/components/course/course-question-snippet/course-question-snippet.component.ts
Labels: refactor
