Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2022-04, with the labels that each got.

#457 Update problem view UI and subscriptions
  src/app/components/tab-list-view-switcher/tab-list-view-switcher.component.html
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.html
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.scss
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.html
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.scss
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.html
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.scss
  src/app/problems/problem-view/problem-view.component.html
  src/app/problems/problem-view/problem-view.component.scss
  src/app/problems/problem-view/problem-view.component.ts
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/app/problems/problem-view/variable-view/variable-view.component.html
Labels: refactor

#459 Update practice problem UI
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/course/course.module.ts
  src/app/course/practice-problem/practice-problem.component.html
  src/app/course/practice-problem/practice-problem.component.scss
  src/app/course/practice-problem/practice-problem.component.ts
Labels: refactor

#465 Fix course filtering
  src/app/course/course-list/course-list.component.html
Labels: bug

#448 Update parsons lines for cases without braces
  package-lock.json
  package.json
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.html
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.scss
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.ts
Labels: bug, refactor

#461 Update error messages for course registration, add error state
  src/app/course/_services/course.service.ts
  src/app/course/course-registration/course-register.component.html
  src/app/course/course-registration/course-register.component.scss
  src/app/course/course-registration/course-register.component.ts
  src/app/course/course.module.ts
  src/app/problems/_services/submission.service.ts
Labels: bug

#463 Problem loading button and problem disabled button
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.html
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.html
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.html
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
Labels: enhancement

#467 Update practice-problem.component.ts
  src/app/course/practice-problem/practice-problem.component.ts
Labels: bug

#474 Upgrade Taiga-UI to fix bugs
  package-lock.json
  package.json
Labels: bug

#478 Reorder variables in problem edit/create
  src/app/problems/json-editor/variables-editor/variables-editor.component.html
  src/app/problems/json-editor/variables-editor/variables-editor.component.scss
  src/app/problems/json-editor/variables-editor/variables-editor.component.ts
Labels: enhancement

#480 Update 404 and 403 pages
  src/app/components/general/forbidden/forbidden.component.html
  src/app/components/general/forbidden/forbidden.component.scss
  src/app/components/general/not-found/not-found.component.html
  src/app/components/general/not-found/not-found.component.scss
Labels: refactor

#469 Practice page navigation
  src/app/course/course.module.ts
  src/app/course/practice-problem/practice-problem.component.html
  src/app/course/practice-problem/practice-problem.component.scss
  src/app/course/practice-problem/practice-problem.component.spec.ts
  src/app/course/practice-problem/practice-problem.component.ts
  src/app/problems/problem-view/problem-view.component.html
Labels: enhancement

#476 Set template input to code editor for java question
  src/app/accounts/consent-form/consent-form.component.spec.ts
  src/app/course/_test/course-event-create-edit/course-event-create-edit.component.spec.ts
  src/app/problems/json-editor/java-input-files-editor/java-input-files-editor.component.html
  src/app/problems/json-editor/java-input-files-editor/java-input-files-editor.component.ts
Labels: enhancement

#484 Update submission view
  src/app/components/code-editor/code-editor.component.html
  src/app/components/code-editor/code-editor.component.ts
  src/app/problems/_test/submission-view/submission-view.component.spec.ts
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.ts
  src/app/problems/problems-routing.module.ts
  src/app/problems/submission-view/submission-view.component.html
  src/app/problems/submission-view/submission-view.component.scss
  src/app/problems/submission-view/submission-view.component.ts
Labels: refactor

#486 Fix course island header
  src/app/components/course-island/course-island.component.scss
Labels: bug

#487 Revert "Add Required Fields to Consent Form"
  src/app/accounts/consent-form/consent-form.component.html
Labels: bug

#491 Override tui-island_hoverable class
  src/scss/styles.scss
  src/scss/tui.scss
Labels: enhancement

#482 Finish admin page
  src/app/admin/admin.component.html
  src/app/admin/admin.component.scss
  src/app/admin/admin.module.ts
  src/app/admin/category-stats/category-stats.component.html
  src/app/admin/category-stats/category-stats.component.scss
  src/app/admin/category-stats/category-stats.component.ts
  src/app/admin/courses/courses.component.html
  src/app/admin/courses/courses.component.scss
  src/app/admin/question-count/question-count.component.html
  src/app/admin/question-count/question-count.component.scss
  src/app/admin/question-count/question-count.component.ts
  src/app/components/header/header.component.html
  src/app/course/practice-problem/practice-problem.component.scss
  src/scss/_mixins.scss
Labels: refactor

#489 Update homepage layout
  src/app/components/homepage/course-dashboard/course-dashboard.component.html
  src/app/components/homepage/homepage.component.html
  src/app/components/homepage/homepage.component.scss
  src/app/components/homepage/inactive-courses/inactive-courses.component.html
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/recent-viewed-questions/recent-viewed-questions.component.html
Labels: refactor

#472 Fix MCQ Bug
  src/app/problems/_test/problem-view/java-view-snippet.component.spec.ts
  src/app/problems/_test/problem-view/mcq-view-snippet.component.spec.ts
  src/app/problems/_test/problem-view/parsons-view-snippet.component.spec.ts
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
Labels: bug

#493 Remove height from sidebar mixin
  src/scss/_mixins.scss
Labels: bug

#495 Update tui-status.pipe.ts
  src/app/_helpers/pipes/tui-status.pipe.spec.ts
  src/app/_helpers/pipes/tui-status.pipe.ts
Labels: bug
