Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2022-02, with the labels that each got.

#363 Problem Practice
  src/app/_models/question.ts
  src/app/_models/user_difficulty_stats.ts
  src/app/_services/api/user-stats.service.spec.ts
  src/app/_services/api/user-stats.service.ts
  src/app/course/_test/mock.ts
  src/app/course/practice-problem/practice-problem.component.html
  src/app/course/practice-problem/practice-problem.component.spec.ts
  src/app/course/practice-problem/practice-problem.component.ts
  src/app/problems/_test/_services/course-event.service.mock.ts
  src/app/problems/_test/mock.ts
  src/test/course.service.mock.ts
  src/test/user-stats.service.mock.ts
Labels: enhancement

#360 Update FAQ page
  src/app/app.module.ts
  src/app/components/faq-accordion/faq-accordion.component.html
  src/app/components/faq-accordion/faq-accordion.component.scss
  src/app/components/faq-accordion/faq-accordion.component.spec.ts
  src/app/components/faq-accordion/faq-accordion.component.ts
  src/app/components/faq-accordion/faq-accordion.module.ts
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.scss
  src/app/components/faq/faq.component.spec.ts
  src/app/components/faq/faq.component.ts
Labels: refactor

#365 Landing page - Taiga UI (Merge FAQ first)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/contact/contact.component.html
  src/app/components/contact/contact.component.scss
  src/app/components/contact/contact.component.spec.ts
  src/app/components/contact/contact.component.ts
  src/app/components/contact/contact.module.ts
  src/app/components/landing-page/landing-page.component.html
  src/app/components/landing-page/landing-page.component.scss
  src/app/components/landing-page/landing-page.component.ts
  src/app/problems/problems.module.ts
  src/assets/global/Logo_Canvas_Red_Vertical.png
Labels: refactor

#367 User Actions Routing
  src/app/_models/action.ts
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/user-actions/user-actions.component.html
  src/test/mock.ts
Labels: bug

#369 Fix dialog not closing when deleting question
  src/app/problems/problem-set/problem-set.component.html
Labels: bug

#371 Remove bootstrap and material from angular compilation
  angular.json
  src/app/app.component.scss
  src/index.html
  src/scss/_mixins.scss
  src/scss/_variables.scss
  src/scss/material/custom-themes.scss
  src/scss/material/global-material-theme.scss
  src/scss/styles.scss
Labels: bug

#373 Change update password button appearance
  src/app/accounts/profile-details/profile-details.component.html
Labels: refactor

#375 Update change password page - Taiga UI
  src/app/accounts/change-password/change-password.component.html
  src/app/accounts/change-password/change-password.component.scss
Labels: refactor

#377 Make field errors values global
  src/app/accounts/consent-form/consent-form.component.ts
  src/app/accounts/login/login.component.ts
  src/app/accounts/profile-details/profile-details.component.ts
  src/app/accounts/register/register.component.ts
  src/app/accounts/reset-password/reset-password.component.ts
  src/app/app.module.ts
  src/app/course/course-registration/course-registration-stepper/course-registration-stepper.component.ts
Labels: refactor

#379 Move night mode to user dropdown
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: refactor

#381 Update User Actions
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/user-actions/user-actions.component.html
Labels: bug, enhancement

#383 Update submission view layout
  src/app/problems/submission-view/submission-view.component.html
  src/app/problems/submission-view/submission-view.component.scss
Labels: refactor

#385 Add tui status pipe to remove duplicate functions
  src/app/_helpers/pipes/pipes.module.ts
  src/app/_helpers/pipes/tui-status.pipe.spec.ts
  src/app/_helpers/pipes/tui-status.pipe.ts
  src/app/problems/_test/submission-view/submission-view.component.spec.ts
  src/app/problems/problem-view/problem-view.component.html
  src/app/problems/problem-view/problem-view.component.ts
  src/app/problems/submission-view/submission-view.component.html
  src/app/problems/submission-view/submission-view.component.ts
Labels: refactor

#390 Fix visual bug with int variable
  src/app/problems/json-editor/variables-editor/variables-editor.component.html
Labels: bug

#393 Replace ACE editor with CodeMirror
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/code-editor/code-editor.component.html
  src/app/components/code-editor/code-editor.component.scss
  src/app/components/code-editor/code-editor.component.spec.ts
  src/app/components/code-editor/code-editor.component.ts
  src/app/components/code-editor/code-editor.module.ts
  src/app/components/landing-page/landing-page.component.html
  src/app/components/landing-page/landing-page.component.scss
  src/app/course/course.module.ts
  src/app/problems/_test/ace/ace.component.spec.ts
  src/app/problems/ace/ace.component.html
  src/app/problems/ace/ace.component.scss
  src/app/problems/ace/ace.component.ts
  src/app/problems/problem-create-edit/java-create-edit-snippet/java-create-edit-snippet.component.html
  src/app/problems/problem-create-edit/parsons-create-edit-snippet/parsons-create-edit-snippet.component.html
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.html
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.scss
  src/app/problems/problems.module.ts
Labels: refactor

#397 Fix Bug with Update Password
  src/app/accounts/change-password/change-password.component.ts
Labels: bug

#401 Upgrade to Angular 13
  .github/workflows/build.yml
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/_helpers/pipes/pipes.module.ts
  src/app/accounts/accounts.module.ts
  src/app/admin/admin.module.ts
  src/app/admin/category-stats/category-stats.component.ts
  src/app/admin/question-count/question-count.component.ts
  src/app/app.module.ts
  src/app/components/contact/contact.module.ts
  src/app/components/course-island/course-island.module.ts
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/user-actions/user-actions.component.html
  src/app/components/homepage/user-actions/user-actions.component.ts
  src/app/components/tab-list-view-switcher/tab-list-view-switcher.module.ts
  src/app/components/topics/topics.component.html
  src/app/components/topics/topics.component.ts
  src/app/course/_test/course-list/course-list.component.spec.ts
  src/app/course/course-list/course-list.component.ts
  src/app/course/course-registration/course-register.component.ts
  src/app/course/course-registration/course-registration-stepper/course-registration-stepper.component.ts
  src/app/course/course.module.ts
  src/app/problems/problem-set/problem-set.component.ts
  src/app/problems/problem-view/parsons-lines/parsons-lines.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
  src/app/problems/problem-view/problem-view.component.ts
  src/app/problems/problems.module.ts
Labels: enhancement

#403 Fix code-editor problem
  src/app/components/code-editor/code-editor.component.ts
Labels: bug

#395 Fix Submissions not Reloading Upon Submission
  src/app/problems/problem-view/java-view-snippet/java-view-snippet.component.ts
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.ts
  src/app/problems/problem-view/parsons-view-snippet/parsons-view-snippet.component.ts
  src/app/problems/problem-view/problem-view.component.html
  src/app/problems/problem-view/problem-view.component.ts
Labels: bug

#404 Indicate No Available Practice Questions
  src/app/course/practice-problem/practice-problem.component.html
Labels: bug

#406 Refactor topics page - Taiga UI
  src/app/components/topics/topics.component.html
  src/app/components/topics/topics.component.scss
  src/app/components/topics/topics.component.ts
Labels: refactor

#408 Fix Angular Migration Issues
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/polyfills.ts
Labels: bug

#410 Update Button Text
  src/app/course/practice-problem/practice-problem.component.html
Labels: bug

#412 Update Category Dropdown
  src/app/course/practice-problem/practice-problem.component.html
Labels: bug

#414 Update Wording of Tokens
  src/app/problems/problem-view/problem-view.component.html
Labels: bug

#416 Add Required Fields to Consent Form
  src/app/accounts/consent-form/consent-form.component.html
Labels: bug

#418 Update Concept Map Title
  src/app/course/_test/concept-map/concept-map.component.spec.ts
  src/app/course/concept-map/concept-map.component.html
Labels: bug
