Repository canvas-gamification/canvas-gamification-ui, pull requests merged in 2022-03, with the labels that each got.

#421 Withdraw consent
  src/app/accounts/profile-details/profile-details.component.html
  src/app/accounts/profile-details/profile-details.component.spec.ts
  src/app/accounts/profile-details/profile-details.component.ts
Labels: bug

#423 Consent form name
  src/app/accounts/_forms/consent.form.ts
  src/app/accounts/consent-form/consent-form.component.spec.ts
  src/app/accounts/consent-form/consent-form.component.ts
Labels: bug

#426 Update Submission Status
  src/app/_models/question_submission.ts
  src/app/problems/_test/mock.ts
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.html
Labels: bug

#428 Add Global Footer
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/components/footer/footer.module.ts
Labels: enhancement

#430 Update Minimum Font Size
  src/app/components/homepage/recent-user-actions/recent-user-actions.component.html
  src/app/components/homepage/recent-viewed-questions/recent-viewed-questions.component.html
  src/app/problems/problem-view/submission-snippet/submission-snippet.component.html
  src/scss/styles.scss
Labels: enhancement

#433 Change max attempts to remaining attempts
  src/app/problems/problem-view/problem-view.component.html
Labels: bug

#438 Update course.component.html
  src/app/course/course.component.html
Labels: bug

#440 Navigate to Practice Page Immediately
  src/app/course/_test/concept-map/concept-map.component.spec.ts
  src/app/course/concept-map/concept-map.component.ts
Labels: bug

#435 Change "Your Success"
  src/app/course/practice-problem/practice-problem.component.html
Labels: bug

#442 Fix titles for concept map and layout
  src/app/course/concept-map/concept-map.component.html
  src/app/course/concept-map/concept-map.component.scss
Labels: bug

#446 Change registration notification message
  src/app/course/course-registration/course-register.component.html
Labels: refactor

#444 Implement Taiga UI New Editor with KaTeX support to replace Quill Editor
  package-lock.json
  package.json
  src/app/_helpers/pipes/get-katex-html-string.pipe.spec.ts
  src/app/_helpers/pipes/get-katex-html-string.pipe.ts
  src/app/_helpers/pipes/get-katex-string.pipe.spec.ts
  src/app/_helpers/pipes/get-katex-string.pipe.ts
  src/app/_helpers/pipes/pipes.module.ts
  src/app/app.module.ts
  src/app/components/editor/editor.component.html
  src/app/components/editor/editor.component.scss
  src/app/components/editor/editor.component.spec.ts
  src/app/components/editor/editor.component.ts
  src/app/components/editor/editor.module.ts
  src/app/components/editor/inline-math/inline-math.component.html
  src/app/components/editor/inline-math/inline-math.component.scss
  src/app/components/editor/inline-math/inline-math.component.spec.ts
  src/app/components/editor/inline-math/inline-math.component.ts
  src/app/components/editor/inline-math/inline-math.extension.ts
  src/app/components/editor/katex-tool/katex-tool.component.html
  src/app/components/editor/katex-tool/katex-tool.component.scss
  src/app/components/editor/katex-tool/katex-tool.component.ts
  src/app/problems/problem-create-edit/java-create-edit-snippet/java-create-edit-snippet.component.html
  src/app/problems/problem-create-edit/mcq-create-edit-snippet/mcq-create-edit-snippet.component.html
  src/app/problems/problem-create-edit/parsons-create-edit-snippet/parsons-create-edit-snippet.component.html
  src/app/problems/problem-view/mcq-view-snippet/mcq-view-snippet.component.html
  src/app/problems/problem-view/problem-view.component.html
  src/app/problems/problem-view/problem-view.component.ts
  src/app/problems/problems.module.ts
  src/scss/styles.scss
Labels: refactor

#450 Attempt making concept map scroll & update styling
  src/app/course/concept-map/concept-map-graph.ts
  src/app/course/concept-map/concept-map.component.html
  src/app/course/concept-map/concept-map.component.scss
Labels: refactor

#452 Add textbox for parsons question input
  src/app/problems/_test/json-editor/parsons-input-files-editor.component.spec.ts
  src/app/problems/json-editor/parsons-input-files-editor/parsons-input-files-editor.component.html
  src/app/problems/json-editor/parsons-input-files-editor/parsons-input-files-editor.component.scss
  src/app/problems/json-editor/parsons-input-files-editor/parsons-input-files-editor.component.ts
  src/app/problems/problems.module.ts
Labels: enhancement

#454 Move course url to left side near the course name
  src/app/course/course.component.html
  src/app/course/course.component.scss
Labels: refactor
